"""
bb_questions.py  -  question bank for Bond Balancer

Every chapter ends up with 90 multiple-choice questions: the ones already in bond_balancer.py plus the
questions below, 30 of which per chapter are extremely difficult. The questions are original and
written to cover the content of Cambridge O-Level Chemistry 5070, Cambridge IGCSE Chemistry 0620 and
Pearson Edexcel International GCSE Chemistry 4CH1 (papers 1C and 2C). They are not copied from
past papers.
"""

NEW_BONDS = [
    ('Which type of bonding is present in sodium chloride?',
     ['Metallic bonding', 'Covalent bonding', 'Ionic bonding', 'Hydrogen bonding'], 'C'),
    ('Why does solid sodium chloride not conduct electricity?',
     ['It is a simple covalent molecule', 'Its ions are held in fixed positions and cannot move', 'Its electrons are held too tightly to move', 'It contains no ions'], 'B'),
    ('Which substance has a giant covalent structure?',
     ['Carbon dioxide', 'Magnesium', 'Sodium chloride', 'Silicon dioxide'], 'D'),
    ('Why can graphite conduct electricity?',
     ['Each carbon atom has four strong bonds', 'It contains free ions', 'It has delocalised electrons between its layers', 'Its layers are held together by ionic bonds'], 'C'),
    ('How many lone pairs of electrons are on the oxygen atom in a water molecule?',
     ['2', '0', '1', '4'], 'A'),
    ('Why do simple molecular substances have low melting points?',
     ['They contain ions that move easily', 'Only weak forces between molecules must be overcome', 'They contain delocalised electrons', 'The covalent bonds inside the molecules are weak'], 'B'),
    ('What is the formula of aluminium oxide?',
     ['Al₂O₂', 'AlO', 'Al₂O₃', 'Al₃O₂'], 'C'),
    ('How is a pure sample of copper(II) sulfate crystals made from copper(II) oxide and dilute sulfuric acid?',
     ['Add the oxide to the acid and titrate with indicator', 'Add sodium sulfate solution to the oxide and evaporate', 'Add excess copper(II) oxide to warm acid, filter, then crystallise the filtrate', 'Add copper metal to the acid and filter'], 'C'),
    ('Which pair of solutions would be mixed to prepare insoluble lead(II) iodide?',
     ['Lead(II) nitrate and potassium iodide', 'Lead(II) oxide and hydrochloric acid', 'Lead metal and iodine solution', 'Lead(II) carbonate and water'], 'A'),
    ('What is the approximate pH of 0.1 mol/dm³ sodium hydroxide solution?',
     ['7', '1', '9', '13'], 'D'),
    ('Which ion is present in all acidic solutions?',
     ['H⁺', 'Cl⁻', 'Na⁺', 'OH⁻'], 'A'),
    ('Which change would increase the rate of reaction between zinc and dilute sulfuric acid?',
     ['Using a larger volume of the same acid', 'Using a more dilute acid', 'Lowering the temperature', 'Using zinc powder instead of zinc granules'], 'D'),
    ('How does a catalyst increase the rate of a reaction?',
     ['It increases the concentration of the reactants', 'It provides an alternative pathway with a lower activation energy', 'It increases the energy of the reactant particles', 'It is used up as the reaction proceeds'], 'B'),
    ('What happens to the temperature of the surroundings in an exothermic reaction?',
     ['It increases', 'It decreases and then increases', 'It stays the same', 'It decreases'], 'A'),
    ('Which process is endothermic?',
     ['Respiration', 'Combustion of methane', 'Neutralisation of hydrochloric acid by sodium hydroxide', 'Thermal decomposition of calcium carbonate'], 'D'),
    ('What is the oxidation state of sulfur in the sulfate ion, SO₄²⁻?',
     ['+6', '−2', '+4', '+2'], 'A'),
    ('In Mg + 2HCl → MgCl₂ + H₂, which species is the reducing agent?',
     ['MgCl₂', 'Mg', 'H₂', 'HCl'], 'B'),
    ('Which metal would displace zinc from zinc sulfate solution?',
     ['Copper', 'Silver', 'Iron', 'Magnesium'], 'D'),
    ('How is iron extracted from iron(III) oxide in the blast furnace?',
     ['Heating the ore on its own', 'Reduction by carbon monoxide', 'Reaction with dilute acid', 'Electrolysis of molten iron(III) oxide'], 'B'),
    ('What does a reversible reaction mean?',
     ['The reaction can only go forwards', 'The reactants are never used up', 'The products can react to re-form the reactants', 'A catalyst is always needed'], 'C'),
    ('Which catalyst is used in the Contact process?',
     ['Vanadium(V) oxide', 'Nickel', 'Iron', 'Platinum'], 'A'),
    ('A gas turns damp red litmus paper blue. It is:',
     ['Ammonia', 'Carbon dioxide', 'Hydrogen chloride', 'Chlorine'], 'A'),
    ('Which solution gives a white precipitate with acidified barium nitrate solution?',
     ['Sodium chloride', 'Sodium nitrate', 'Sodium carbonate', 'Sodium sulfate'], 'D'),
    ('Which statement describes the structure of solid sodium chloride?',
     ['Positive ions surrounded by a sea of delocalised electrons', 'A giant lattice of alternating positive and negative ions', 'Separate NaCl molecules held together by weak forces', 'A lattice of atoms sharing pairs of electrons'], 'B'),
    ('Which statement about the reactivity series is correct?',
     ['Copper is more reactive than zinc', 'Iron is more reactive than magnesium', 'Potassium is more reactive than calcium', 'Gold reacts violently with cold water'], 'C'),
]

HARD_BONDS = [
    ('Acidified potassium manganate(VII) oxidises iron(II) ions. What is the change in oxidation state of manganese?',
     ['+7 to +4', '+6 to +2', '+7 to +2', '+7 to 0'], 'C'),
    ('In which reaction does hydrochloric acid act as an oxidising agent?',
     ['NaOH + HCl → NaCl + H₂O', 'CaCO₃ + 2HCl → CaCl₂ + H₂O + CO₂', 'MnO₂ + 4HCl → MnCl₂ + Cl₂ + 2H₂O', 'Zn + 2HCl → ZnCl₂ + H₂'], 'D'),
    ('N₂ + 3H₂ ⇌ 2NH₃ (ΔH = −92 kJ/mol). Which change increases BOTH the rate and the equilibrium yield of ammonia?',
     ['Increasing the pressure', 'Increasing the temperature', 'Adding a catalyst', 'Removing nitrogen from the mixture'], 'A'),
    ('2SO₂ + O₂ ⇌ 2SO₃ is exothermic. Why is the Contact process run at only 1–2 atmospheres?',
     ['Pressure has no effect on this equilibrium', 'High pressure would shift the equilibrium towards the reactants', 'High pressure would poison the catalyst', 'The yield is already very high at this pressure, so the cost of high pressure is not justified'], 'D'),
    ('Bond energies (kJ/mol): H–H 436, Cl–Cl 242, H–Cl 431. What is ΔH for H₂ + Cl₂ → 2HCl?',
     ['−92 kJ/mol', '−184 kJ/mol', '+184 kJ/mol', '−862 kJ/mol'], 'B'),
    ('Bond energies (kJ/mol): C–H 413, O=O 498, C=O 805, O–H 464. What is ΔH for CH₄ + 2O₂ → CO₂ + 2H₂O?',
     ['−2 648 kJ/mol', '−818 kJ/mol', '−358 kJ/mol', '+818 kJ/mol'], 'B'),
    ('The rate of a reaction doubles for every 10 °C rise in temperature. It takes 80 s at 20 °C. About how long will it take at 50 °C?',
     ['27 s', '20 s', '40 s', '10 s'], 'D'),
    ('A catalyst is added to an exothermic reaction. What happens to ΔH and to the activation energy?',
     ['ΔH is unchanged and the activation energy increases', 'ΔH becomes less negative and the activation energy is unchanged', 'ΔH becomes more negative and the activation energy decreases', 'ΔH is unchanged and the activation energy decreases'], 'D'),
    ('Which ions are the spectator ions when aqueous copper(II) sulfate reacts with aqueous sodium hydroxide?',
     ['Cu²⁺ and OH⁻', 'Na⁺ and SO₄²⁻', 'Cu²⁺ and SO₄²⁻', 'Na⁺ and OH⁻'], 'B'),
    ('A solution gives a white precipitate with sodium hydroxide that dissolves in excess, and a white precipitate with ammonia solution that also dissolves in excess. The cation is:',
     ['Al³⁺', 'Zn²⁺', 'Ca²⁺', 'Mg²⁺'], 'B'),
    ('A white solid fizzes with dilute hydrochloric acid, giving a gas that turns limewater milky. The solid gives a brick-red flame. The solid is:',
     ['Calcium carbonate', 'Copper(II) carbonate', 'Sodium carbonate', 'Barium carbonate'], 'A'),
    ('Why does magnesium oxide have a much higher melting point than sodium chloride?',
     ['Mg²⁺ and O²⁻ have higher charges, so the electrostatic attraction between ions is stronger', 'Magnesium oxide has a giant covalent structure', 'Magnesium atoms form metallic bonds in magnesium oxide', 'Magnesium oxide has a larger relative formula mass'], 'A'),
    ('Why does silicon dioxide have a very high melting point while carbon dioxide has a very low one?',
     ['SiO₂ has delocalised electrons and CO₂ does not', 'The covalent bonds in CO₂ are weaker than those in SiO₂', 'SiO₂ is ionic and CO₂ is covalent', 'SiO₂ has strong covalent bonds throughout a giant structure; CO₂ has weak forces between small molecules'], 'D'),
    ('Why can carbon not be used to extract aluminium from aluminium oxide?',
     ['Aluminium oxide has too low a melting point', 'Aluminium is more reactive than carbon, so carbon cannot remove the oxygen', 'Aluminium oxide is insoluble', 'Carbon reacts with aluminium to form a carbide only'], 'B'),
    ('2NO₂ (brown) ⇌ N₂O₄ (colourless), ΔH = −57 kJ/mol. A sealed tube of the mixture is cooled in ice. What is observed?',
     ['The gas turns blue', 'The colour becomes darker brown', 'The colour becomes paler', 'The colour does not change'], 'C'),
    ('Which oxide is amphoteric?',
     ['Carbon dioxide', 'Aluminium oxide', 'Sodium oxide', 'Magnesium oxide'], 'B'),
    ('Manganese(IV) oxide is added to hydrogen peroxide solution and the gas is collected. What is true of the manganese(IV) oxide at the end?',
     ['It has turned into manganese(II) oxide', 'It has the same mass and is chemically unchanged', 'It has a smaller mass because it reacted', 'It has dissolved completely'], 'B'),
    ('In the reaction 2KI + Cl₂ → 2KCl + I₂, which species is oxidised?',
     ['Iodide ions, because they lose electrons', 'Potassium ions, because they gain electrons', 'Chlorine molecules, because they lose electrons', 'Chloride ions, because they gain electrons'], 'A'),
    ('A white solid gives off a gas that turns limewater milky when heated. The residue is yellow when hot and white when cold. The solid is:',
     ['Zinc carbonate', 'Copper(II) carbonate', 'Calcium carbonate', 'Sodium carbonate'], 'A'),
    ('Sulfur dioxide is bubbled through acidified potassium manganate(VII). What is observed?',
     ['There is no change', 'The colourless solution turns purple', 'The orange solution turns green', 'The purple solution becomes colourless'], 'D'),
    ('Excess dilute HCl reacts with 5 g of marble chips (experiment 1) and 5 g of powdered marble (experiment 2). Which statement about graphs of gas volume against time is correct?',
     ['Both start with the same gradient but end at different volumes', 'Experiment 2 reaches a larger final volume', 'Both reach the same final volume, but experiment 2 is steeper at the start', 'Experiment 2 has a less steep curve at the start'], 'C'),
    ('A solution gives a white precipitate with acidified silver nitrate and a different white precipitate with acidified barium nitrate. Which ions are present?',
     ['Chloride and sulfate', 'Chloride only', 'Carbonate and chloride', 'Sulfate and nitrate'], 'A'),
    ('A few drops of copper(II) sulfate solution speed up the reaction of zinc with dilute sulfuric acid. Why?',
     ['Copper(II) sulfate raises the temperature of the acid', 'Zinc displaces copper, and the copper formed acts as a catalyst', 'Copper(II) sulfate is a reactant that reacts with the acid', 'Copper(II) sulfate increases the concentration of H⁺ ions'], 'B'),
    ('Hydrochloric acid and ethanoic acid have the same concentration. Which statement is correct?',
     ['Hydrochloric acid has the lower pH because it ionises completely', 'They have the same pH because they have the same concentration', 'Hydrochloric acid has the higher pH because it is the stronger acid', 'Ethanoic acid has the lower pH because it contains more hydrogen atoms'], 'A'),
    ('Equal volumes of 0.1 mol/dm³ hydrochloric acid and 0.1 mol/dm³ ethanoic acid react with excess magnesium. Which statement is correct?',
     ['Hydrochloric acid gives twice the volume of hydrogen', 'Both the rate and the total volume of hydrogen are the same', 'The initial rate is faster with hydrochloric acid, but the total volume of hydrogen is the same', 'The initial rate is faster with ethanoic acid'], 'C'),
    ('Which salt is best prepared by titration of an acid with an alkali?',
     ['Sodium nitrate', 'Barium sulfate', 'Silver chloride', 'Copper(II) carbonate'], 'A'),
    ('Why is brass harder than pure copper?',
     ['Brass contains no delocalised electrons', 'Brass contains ionic bonds', 'Atoms of a different size disrupt the regular layers, so the layers slide less easily', 'Brass atoms are all the same size'], 'C'),
    ('Fe₂O₃ + 2Al → Al₂O₃ + 2Fe. Which statement is correct?',
     ['No redox takes place because oxygen is only exchanged', 'Aluminium is reduced and iron(III) oxide is oxidised', 'Aluminium is oxidised and iron(III) ions are reduced', 'Both aluminium and iron are reduced'], 'C'),
    ('Which compound is covalent but forms ions when it dissolves in water, so its solution conducts electricity?',
     ['Sucrose', 'Tetrachloromethane', 'Hydrogen chloride', 'Methane'], 'C'),
    ('Bond energies (kJ/mol): H–H 436, I–I 151, H–I 299. What is ΔH for H₂ + I₂ → 2HI?',
     ['−598 kJ/mol', '−299 kJ/mol', '+11 kJ/mol', '−11 kJ/mol'], 'D'),
]

NEW_ATOMIC = [
    ('An atom of sodium has atomic number 11 and mass number 23. How many neutrons does it contain?',
     ['34', '11', '23', '12'], 'D'),
    ('An atom of potassium has atomic number 19 and mass number 39. How many neutrons does it contain?',
     ['39', '19', '20', '58'], 'C'),
    ('An atom of iron has atomic number 26 and mass number 56. How many neutrons does it contain?',
     ['26', '30', '56', '82'], 'B'),
    ('An atom of silver has atomic number 47 and mass number 108. How many neutrons does it contain?',
     ['47', '108', '155', '61'], 'D'),
    ('An atom of bromine has atomic number 35 and mass number 80. How many neutrons does it contain?',
     ['80', '115', '35', '45'], 'D'),
    ('How many electrons are in one Mg²⁺ ion? (Atomic number of the element = 12)',
     ['10', '14', '8', '12'], 'A'),
    ('How many electrons are in one O²⁻ ion? (Atomic number of the element = 8)',
     ['10', '20', '4', '8'], 'A'),
    ('How many electrons are in one Al³⁺ ion? (Atomic number of the element = 13)',
     ['7', '10', '16', '13'], 'B'),
    ('How many electrons are in one Cl⁻ ion? (Atomic number of the element = 17)',
     ['18', '17', '36', '15'], 'A'),
    ('How many electrons are in one S²⁻ ion? (Atomic number of the element = 16)',
     ['18', '12', '16', '36'], 'A'),
    ('What is the electronic configuration of an atom with atomic number 9?',
     ['2,8', '2,7', '7', '2,6'], 'B'),
    ('What is the electronic configuration of an atom with atomic number 13?',
     ['2,8,3', '2,8,4', '2,3', '2,8,2'], 'A'),
    ('What is the electronic configuration of an atom with atomic number 15?',
     ['2,5', '2,8,5', '2,8,3', '2,8,7'], 'B'),
    ('What is the electronic configuration of an atom with atomic number 17?',
     ['2,8,7', '2,8,6', '2,8,8', '2,7'], 'A'),
    ('What is the electronic configuration of an atom with atomic number 20?',
     ['2,8,8', '2,8,2', '2,8,8,2', '2,8,10'], 'C'),
    ('In which group and period is the element with atomic number 12?',
     ['Group II, Period 2', 'Group III, Period 2', 'Group III, Period 3', 'Group II, Period 3'], 'D'),
    ('In which group and period is the element with atomic number 16?',
     ['Group VI, Period 2', 'Group III, Period 6', 'Group VI, Period 3', 'Group IV, Period 3'], 'C'),
    ('In which group and period is the element with atomic number 19?',
     ['Group IV, Period 1', 'Group II, Period 4', 'Group I, Period 3', 'Group I, Period 4'], 'D'),
    ('A sample of chlorine contains 75% ³⁵Cl and 25% ³⁷Cl. What is the relative atomic mass of chlorine?',
     ['37', '35', '35.5', '36'], 'C'),
    ('A sample of boron contains 20% ¹⁰B and 80% ¹¹B. What is the relative atomic mass of boron?',
     ['10.8', '10.2', '11', '10.5'], 'A'),
    ('What are the relative charges of a proton, a neutron and an electron?',
     ['0, +1, −1', '−1, 0, +1', '+1, −1, 0', '+1, 0, −1'], 'D'),
    ('Why do isotopes of the same element have the same chemical properties?',
     ['They have different numbers of protons', 'They have the same number of neutrons', 'They have the same mass number', 'They have the same number of electrons in the outer shell'], 'D'),
    ('Why are atoms electrically neutral?',
     ['Electrons are not charged', 'They contain equal numbers of protons and neutrons', 'They contain equal numbers of protons and electrons', 'Neutrons cancel the charge of the protons'], 'C'),
    ('Which physical property decreases down Group I?',
     ['Reactivity with water', 'Atomic radius', 'Number of electron shells', 'Melting point'], 'D'),
    ('What is observed when a small piece of lithium is added to water?',
     ['It burns with a lilac flame', 'It floats, fizzes and the solution becomes alkaline', 'It sinks and reacts explosively', 'There is no reaction'], 'B'),
    ('Which halogen is a liquid at room temperature?',
     ['Fluorine', 'Iodine', 'Bromine', 'Chlorine'], 'C'),
    ('What colour is iodine vapour?',
     ['Red-brown', 'Purple', 'Pale yellow', 'Green'], 'B'),
    ('Which reaction takes place?',
     ['I₂ + 2KCl → 2KI + Cl₂', 'Br₂ + 2KCl → 2KBr + Cl₂', 'Cl₂ + 2KI → 2KCl + I₂', 'I₂ + 2KBr → 2KI + Br₂'], 'C'),
    ('Which noble gas is used to fill filament lamps?',
     ['Xenon', 'Argon', 'Helium', 'Neon'], 'B'),
    ('Which is a typical property of transition metals?',
     ['They are very soft', 'They form coloured compounds', 'They form only colourless ions', 'They have low melting points'], 'B'),
    ('Which transition metal is used as the catalyst in the Haber process?',
     ['Iron', 'Platinum', 'Nickel', 'Copper'], 'A'),
    ('What happens to the nature of the oxides across Period 3, from sodium to chlorine?',
     ['They change from basic to acidic', 'They are all basic', 'They change from acidic to basic', 'They are all acidic'], 'A'),
    ('Which Period 3 element is a semiconductor?',
     ['Argon', 'Phosphorus', 'Sodium', 'Silicon'], 'D'),
    ('In the modern periodic table the elements are arranged in order of:',
     ['Increasing density', 'Increasing relative atomic mass', 'Increasing number of neutrons', 'Increasing atomic number'], 'D'),
    ('Why did Mendeleev leave gaps in his periodic table?',
     ['The elements there were radioactive', 'He did not know their atomic masses', 'He predicted that undiscovered elements would fill them', 'They were reserved for the noble gases'], 'C'),
    ('Which element is in Group II and Period 3?',
     ['Calcium', 'Magnesium', 'Beryllium', 'Aluminium'], 'B'),
    ('Which of these forms an ion with the same electron arrangement as argon?',
     ['Oxygen, forming O²⁻', 'Lithium, forming Li⁺', 'Sodium, forming Na⁺', 'Calcium, forming Ca²⁺'], 'D'),
    ('Which particle has 12 protons, 12 neutrons and 10 electrons?',
     ['²⁴Mg', '²³Na⁺', '²⁴Mg²⁺', '²²Ne'], 'C'),
    ('What is the relative atomic mass of an element?',
     ['The number of protons and neutrons in its most common isotope', 'The mass of one mole of its atoms divided by 12', 'The mass of one atom in grams', 'The weighted average mass of its atoms compared with 1/12 of the mass of a carbon-12 atom'], 'D'),
    ('What is the electronic configuration of a Ca²⁺ ion?',
     ['2,8', '2,8,8,2', '2,8,8', '2,8,10'], 'C'),
    ('What are Group I compounds like?',
     ['Coloured covalent liquids', 'White ionic solids that dissolve in water', 'Insoluble ionic solids', 'Black solids that conduct electricity'], 'B'),
    ('What is observed when calcium is added to water?',
     ['A steady stream of bubbles and the solution turns cloudy', 'No visible change', 'A lilac flame and violent explosion', 'The metal floats and melts into a ball'], 'A'),
    ('What is the appearance of chlorine at room temperature?',
     ['A pale green gas', 'A red-brown liquid', 'A grey solid', 'A colourless gas'], 'A'),
    ('Why is helium used to fill balloons?',
     ['It is much less dense than air and unreactive', 'It is denser than air', 'It is a liquid at room temperature', 'It is more reactive than air'], 'A'),
    ('How do the boiling points of the noble gases change down Group 0?',
     ['They decrease', 'They stay the same', 'They increase', 'They increase and then decrease'], 'C'),
    ('Why are sodium and potassium stored under oil?',
     ['They dissolve in air', 'They react with oxygen and water in the air', 'They are radioactive', 'They are poisonous gases'], 'B'),
    ('Which metal is a liquid at room temperature?',
     ['Zinc', 'Tin', 'Mercury', 'Lead'], 'C'),
    ('Why do halogens exist as diatomic molecules?',
     ['They form giant lattices', 'Two atoms share a pair of electrons to fill their outer shells', 'They transfer electrons between atoms', 'They have metallic bonding'], 'B'),
]

HARD_ATOMIC = [
    ('Magnesium contains 79% ²⁴Mg, 10% ²⁵Mg and 11% ²⁶Mg. What is its relative atomic mass?',
     ['24.3', '24', '25', '24.5'], 'A'),
    ('Silicon contains 92.2% ²⁸Si, 4.7% ²⁹Si and 3.1% ³⁰Si. What is its relative atomic mass?',
     ['28.5', '28.1', '28', '29'], 'B'),
    ('Copper has two isotopes, ⁶³Cu and ⁶⁵Cu. Its relative atomic mass is 63.6. What is the percentage of ⁶⁵Cu?',
     ['36%', '30%', '60%', '70%'], 'B'),
    ('Lithium has two isotopes, ⁶Li and ⁷Li. Its relative atomic mass is 6.9. What is the percentage of ⁷Li?',
     ['69%', '90%', '50%', '45%'], 'B'),
    ('Boron has two isotopes, ¹⁰B and ¹¹B. Its relative atomic mass is 10.8. What is the percentage of ¹⁰B?',
     ['80%', '40%', '90%', '20%'], 'D'),
    ('Why is potassium more reactive than lithium?',
     ['Its outer electron is further from the nucleus and more shielded, so it is lost more easily', 'It has more protons, which attract the outer electron more strongly', 'It has fewer electron shells', 'Its atoms are smaller'], 'A'),
    ('Why does the reactivity of the halogens decrease down Group VII?',
     ['The atoms lose electrons more easily', 'The nuclear charge decreases', 'The molecules become smaller', 'The outer shell is further from the nucleus, so an electron is gained less easily'], 'D'),
    ('Which prediction about astatine (Group VII, below iodine) is most reasonable?',
     ['A dark solid that would not displace iodine from potassium iodide', 'A red-brown liquid that displaces bromine from potassium bromide', 'A green gas that reacts violently with water', 'A pale yellow gas that would displace iodine from potassium iodide'], 'A'),
    ('Francium lies below caesium in Group I. Which statement about its reaction with water is most reasonable?',
     ['It does not react with water', 'It forms an acidic solution', 'It reacts more slowly than sodium', 'It reacts even more violently than caesium to form an alkaline solution and hydrogen'], 'D'),
    ('How do transition metals compare with Group I metals?',
     ['They have lower melting points and are more reactive', 'They have higher melting points and densities and are less reactive', 'They are softer and less dense', 'They are more reactive and form only white compounds'], 'B'),
    ('The ion X²⁺ has the electronic configuration 2,8,8. What is the atomic number of X?',
     ['18', '22', '10', '20'], 'D'),
    ('An ion has 18 electrons and a charge of 3−. How many protons are in its nucleus?',
     ['18', '21', '15', '3'], 'C'),
    ('Which pair of ions has the same electronic configuration?',
     ['Na⁺ and F⁻', 'Na⁺ and Cl⁻', 'Mg²⁺ and S²⁻', 'Li⁺ and O²⁻'], 'A'),
    ('Which oxide dissolves in water to give a strongly alkaline solution (pH about 14)?',
     ['Sodium oxide', 'Magnesium oxide', 'Phosphorus(V) oxide', 'Aluminium oxide'], 'A'),
    ('Which oxide reacts with both hydrochloric acid and sodium hydroxide solution?',
     ['Magnesium oxide', 'Aluminium oxide', 'Phosphorus(V) oxide', 'Sodium oxide'], 'B'),
    ('An atom has the electronic configuration 2,8,18,7. Which element is it?',
     ['Chlorine, a Group VII gas', 'Krypton, a Group 0 gas', 'Iodine, a Group VII solid', 'Bromine, a Group VII liquid'], 'D'),
    ('Aqueous bromine is added separately to aqueous sodium chloride and aqueous sodium iodide. What is observed?',
     ['A brown colour with sodium chloride; no change with sodium iodide', 'No change with either', 'A brown colour with both', 'No change with sodium chloride; a brown colour with sodium iodide'], 'D'),
    ('Which compound gives a lilac flame colour?',
     ['Sodium chloride', 'Lithium chloride', 'Potassium chloride', 'Calcium chloride'], 'C'),
    ('Why is hydrogen sometimes placed in Group I of the periodic table?',
     ['It has one electron in its outer shell and can form a 1+ ion', 'It reacts violently with water', 'It has a very high melting point', 'It is a reactive metal'], 'A'),
    ('How many protons are there in 1.00 mol of ammonia, NH₃? (Avogadro constant = 6.02 × 10²³ per mol)',
     ['1.20 × 10²⁵', '2.41 × 10²⁴', '6.02 × 10²⁴', '1.02 × 10²⁵'], 'C'),
    ('How many electrons are there in 1.00 mol of carbon dioxide molecules? (Avogadro constant = 6.02 × 10²³ per mol)',
     ['2.65 × 10²⁵', '6.62 × 10²⁴', '1.32 × 10²⁵', '9.63 × 10²⁴'], 'C'),
    ('How many neutrons are there in 1.00 mol of ¹⁴N atoms? (Avogadro constant = 6.02 × 10²³ per mol)',
     ['2.11 × 10²⁴', '4.21 × 10²⁴', '1.26 × 10²⁵', '8.43 × 10²⁴'], 'B'),
    ('How many neutrons are there in 1.00 mol of ²³Na⁺ ions? (Avogadro constant = 6.02 × 10²³ per mol)',
     ['6.02 × 10²⁴', '6.62 × 10²⁴', '7.22 × 10²⁴', '1.38 × 10²⁵'], 'C'),
    ('Which isotope has twice as many neutrons as protons?',
     ['Deuterium, ²H', 'Tritium, ³H', 'Protium, ¹H', 'Helium-4, ⁴He'], 'B'),
    ('Which Period 3 element has the highest melting point?',
     ['Aluminium', 'Sulfur', 'Silicon', 'Magnesium'], 'C'),
    ('Which pair of ions both contain 18 electrons?',
     ['K⁺ and S²⁻', 'Ca²⁺ and F⁻', 'Mg²⁺ and Ar', 'Na⁺ and Cl⁻'], 'A'),
    ('What is the electronic configuration of the ion formed by the Group VI element in Period 3?',
     ['2,8,4', '2,8,8', '2,8', '2,8,6'], 'B'),
    ('Excess sodium hydroxide is added to a solution of an iron salt. A green precipitate forms that turns brown on standing in air. Which ion is present?',
     ['Zn²⁺', 'Cu²⁺', 'Fe²⁺', 'Fe³⁺'], 'C'),
    ('A halide gives a cream precipitate with acidified silver nitrate that dissolves in concentrated, but not dilute, ammonia. Which halide is it?',
     ['Bromide', 'Chloride', 'Iodide', 'Fluoride'], 'A'),
    ('Which Group II metal reacts most vigorously with cold water?',
     ['Calcium', 'Beryllium', 'Magnesium', 'Barium'], 'D'),
]

NEW_MOLES = [
    ('How many moles are in 10 g of NaOH? (Ar: Na = 23, O = 16, H = 1)',
     ['0.5 mol', '0.25 mol', '0.125 mol', '0.375 mol'], 'B'),
    ('How many moles are in 5.3 g of Na₂CO₃? (Ar: Na = 23, C = 12, O = 16)',
     ['0.1 mol', '0.05 mol', '0.075 mol', '0.025 mol'], 'B'),
    ('How many moles are in 4.9 g of H₂SO₄? (Ar: H = 1, S = 32, O = 16)',
     ['0.075 mol', '0.05 mol', '0.025 mol', '0.1 mol'], 'B'),
    ('What is the mass of 0.2 mol of KOH? (Ar: K = 39, O = 16, H = 1)',
     ['16.8 g', '5.6 g', '22.4 g', '11.2 g'], 'D'),
    ('What is the mass of 2.5 mol of H₂O? (Ar: H = 1, O = 16)',
     ['45 g', '90 g', '67.5 g', '22.5 g'], 'A'),
    ('What is the mass of 0.05 mol of CaCO₃? (Ar: C = 12, Ca = 40, O = 16)',
     ['5 g', '10 g', '7.5 g', '2.5 g'], 'A'),
    ('What is the relative formula mass (Mr) of (NH₄)₂SO₄? (Ar: N = 14, H = 1, S = 32, O = 16)',
     ['116', '132', '114', '150'], 'B'),
    ('What is the relative formula mass (Mr) of Al₂(SO₄)₃? (Ar: Al = 27, S = 32, O = 16)',
     ['150', '326', '360', '342'], 'D'),
    ('What is the relative formula mass (Mr) of MgSO₄·7H₂O? (Ar: Mg = 24, S = 32, O = 16, H = 1)',
     ['246', '230', '264', '228'], 'A'),
    ('What is the relative formula mass (Mr) of Ca₃(PO₄)₂? (Ar: Ca = 40, P = 31, O = 16)',
     ['215', '294', '310', '328'], 'C'),
    ('How many atoms are in 0.50 mol of helium? (Avogadro constant = 6.02 × 10²³ per mol)',
     ['3.01 × 10²³', '6.02 × 10²³', '1.20 × 10²⁴', '1.51 × 10²³'], 'A'),
    ('How many molecules are in 0.10 mol of water? (Avogadro constant = 6.02 × 10²³ per mol)',
     ['1.81 × 10²³', '1.20 × 10²³', '6.02 × 10²²', '3.01 × 10²²'], 'C'),
    ('How many oxygen atoms are in 0.20 mol of carbon dioxide? (Avogadro constant = 6.02 × 10²³ per mol)',
     ['3.61 × 10²³', '4.82 × 10²³', '2.41 × 10²³', '1.20 × 10²³'], 'C'),
    ('What volume does 0.25 mol of any gas occupy at room temperature and pressure? (1 mol of gas = 24 dm³)',
     ['3 dm³', '12 dm³', '5.6 dm³', '6 dm³'], 'D'),
    ('What volume does 4.4 g of carbon dioxide occupy at r.t.p.? (Ar: C = 12, O = 16; 1 mol of gas = 24 dm³)',
     ['2.4 dm³', '4.8 dm³', '1.2 dm³', '8.8 dm³'], 'A'),
    ('What volume does 3.2 g of methane, CH₄, occupy at r.t.p.? (Ar: C = 12, H = 1; 1 mol of gas = 24 dm³)',
     ['4.48 dm³', '9.6 dm³', '2.4 dm³', '4.8 dm³'], 'D'),
    ('What mass of ammonia, NH₃, is in 6.0 dm³ of the gas at r.t.p.? (Ar: N = 14, H = 1; 1 mol of gas = 24 dm³)',
     ['3.5 g', '4.25 g', '2.83 g', '8.5 g'], 'B'),
    ('A 25.0 cm³ sample of solution contains 0.0050 mol of solute. What is its concentration?',
     ['0.2 mol/dm³', '0.4 mol/dm³', '0.1 mol/dm³', '0.125 mol/dm³'], 'A'),
    ('2.0 g of sodium hydroxide is dissolved to make 500 cm³ of solution. What is its concentration? (Ar: Na = 23, O = 16, H = 1)',
     ['0.15 mol/dm³', '0.05 mol/dm³', '0.1 mol/dm³', '0.2 mol/dm³'], 'C'),
    ('What mass of sodium hydroxide is in 250 cm³ of a 0.20 mol/dm³ solution? (Ar: Na = 23, O = 16, H = 1)',
     ['2 g', '1 g', '4 g', '8 g'], 'A'),
    ('A hydrochloric acid solution contains 3.65 g/dm³ of HCl. What is its concentration in mol/dm³? (Ar: H = 1, Cl = 35.5)',
     ['0.05 mol/dm³', '0.1 mol/dm³', '0.2 mol/dm³', '0.15 mol/dm³'], 'B'),
    ('What is the concentration in g/dm³ of a 0.50 mol/dm³ solution of sodium hydroxide? (Ar: Na = 23, O = 16, H = 1)',
     ['80 g/dm³', '40 g/dm³', '10 g/dm³', '20 g/dm³'], 'D'),
    ('A sulfuric acid solution contains 9.8 g/dm³ of H₂SO₄. What is its concentration in mol/dm³? (Ar: H = 1, S = 32, O = 16)',
     ['0.1 mol/dm³', '0.05 mol/dm³', '0.15 mol/dm³', '0.2 mol/dm³'], 'A'),
    ('20.0 cm³ of a 1.00 mol/dm³ solution is diluted with water to 100 cm³. What is the new concentration?',
     ['0.2 mol/dm³', '0.4 mol/dm³', '0.25 mol/dm³', '0.05 mol/dm³'], 'A'),
    ('What volume of 2.0 mol/dm³ acid is needed to make 250 cm³ of 0.40 mol/dm³ acid?',
     ['25 cm³', '50 cm³', '200 cm³', '100 cm³'], 'B'),
    ('What is the percentage by mass of nitrogen in ammonium nitrate, NH₄NO₃? (Ar: N = 14, H = 1, O = 16)',
     ['45.2%', '17.5%', '70%', '35%'], 'D'),
    ('What is the percentage by mass of iron in iron(III) oxide, Fe₂O₃? (Ar: Fe = 56, O = 16)',
     ['70%', '30%', '52.5%', '35%'], 'A'),
    ('What is the percentage by mass of oxygen in water? (Ar: H = 1, O = 16)',
     ['44.4%', '88.9%', '94.1%', '47.1%'], 'B'),
    ('A compound contains 2.4 g of magnesium and 1.6 g of oxygen. What is its empirical formula? (Ar: Mg = 24, O = 16)',
     ['Mg₂O₃', 'MgO', 'MgO₂', 'Mg₂O'], 'B'),
    ('A compound contains 5.6 g of iron and 2.4 g of oxygen. What is its empirical formula? (Ar: Fe = 56, O = 16)',
     ['Fe₃O₄', 'Fe₂O₃', 'FeO', 'Fe₂O'], 'B'),
    ('A hydrocarbon contains 6.0 g of carbon and 1.0 g of hydrogen. What is its empirical formula? (Ar: C = 12, H = 1)',
     ['CH', 'C₆H', 'CH₂', 'C₂H'], 'C'),
    ('2Mg + O₂ → 2MgO. What mass of magnesium oxide is formed when 6.0 g of magnesium burns completely? (Ar: Mg = 24, O = 16)',
     ['20 g', '5 g', '10 g', '22 g'], 'C'),
    ('CaCO₃ → CaO + CO₂. What mass of calcium oxide is made by heating 25 g of calcium carbonate? (Ar: Ca = 40, C = 12, O = 16)',
     ['28 g', '25 g', '11 g', '14 g'], 'D'),
    ('Fe₂O₃ + 3CO → 2Fe + 3CO₂. What mass of iron is made from 80 g of iron(III) oxide? (Ar: Fe = 56, O = 16)',
     ['56 g', '84 g', '160 g', '28 g'], 'A'),
    ('CaCO₃ + 2HCl → CaCl₂ + H₂O + CO₂. What volume of CO₂ at r.t.p. is made from 10 g of CaCO₃? (Ar: Ca = 40, C = 12, O = 16; 1 mol of gas = 24 dm³)',
     ['5.45 dm³', '2.24 dm³', '2.4 dm³', '4.8 dm³'], 'C'),
    ('Zn + H₂SO₄ → ZnSO₄ + H₂. What volume of hydrogen at r.t.p. is made from 3.25 g of zinc? (Ar: Zn = 65; 1 mol of gas = 24 dm³)',
     ['1.12 dm³', '0.6 dm³', '2.4 dm³', '1.2 dm³'], 'D'),
    ('2H₂O₂ → 2H₂O + O₂. What volume of oxygen at r.t.p. is made from 3.4 g of hydrogen peroxide? (Ar: H = 1, O = 16; 1 mol of gas = 24 dm³)',
     ['2.4 dm³', '1.12 dm³', '4.8 dm³', '1.2 dm³'], 'D'),
    ('25.0 cm³ of sodium hydroxide solution is neutralised by 20.0 cm³ of 0.100 mol/dm³ hydrochloric acid. What is the concentration of the alkali?',
     ['0.16 mol/dm³', '0.04 mol/dm³', '0.125 mol/dm³', '0.08 mol/dm³'], 'D'),
    ('25.0 cm³ of sodium hydroxide solution is neutralised by 20.0 cm³ of 0.050 mol/dm³ sulfuric acid. What is the concentration of the alkali?',
     ['0.0625 mol/dm³', '0.08 mol/dm³', '0.04 mol/dm³', '0.16 mol/dm³'], 'B'),
    ('20.0 cm³ of 0.100 mol/dm³ sodium carbonate is neutralised by 0.250 mol/dm³ hydrochloric acid (Na₂CO₃ + 2HCl → 2NaCl + H₂O + CO₂). What volume of acid is needed?',
     ['8 cm³', '32 cm³', '20 cm³', '16 cm³'], 'D'),
    ('The theoretical yield of a product is 20 g. The actual yield is 15 g. What is the percentage yield?',
     ['37.5%', '25%', '75%', '42.9%'], 'C'),
    ('12.0 g of magnesium burns to form 18.0 g of magnesium oxide. The theoretical yield is 20.0 g. What is the percentage yield?',
     ['60%', '45%', '90%', '67.5%'], 'C'),
    ('In the Haber process the theoretical yield of ammonia is 34 g but only 6.8 g is obtained. What is the percentage yield?',
     ['20%', '40%', '16.7%', '93.2%'], 'A'),
    ('CaCO₃ → CaO + CO₂. What is the atom economy for making calcium oxide? (Ar: Ca = 40, C = 12, O = 16)',
     ['84%', '28%', '56%', '44%'], 'C'),
    ('Fe₂O₃ + 3CO → 2Fe + 3CO₂. What is the atom economy for making iron? (Ar: Fe = 56, C = 12, O = 16)',
     ['84.8%', '45.9%', '91.8%', '70%'], 'B'),
    ("What does Avogadro's law state?",
     ['Gases always react in equal volumes', 'Equal masses of gases contain the same number of molecules', 'One mole of any gas has a volume of 22.4 dm³ at all temperatures', 'Equal volumes of gases at the same temperature and pressure contain the same number of molecules'], 'D'),
    ('Which sample contains the greatest number of molecules? (Ar: H = 1, C = 12, O = 16)',
     ['1.0 g of carbon dioxide, CO₂', '1.0 g of oxygen, O₂', '1.0 g of hydrogen, H₂', '1.0 g of methane, CH₄'], 'C'),
    ('Why is the actual yield of a reaction usually less than the theoretical yield?',
     ['The law of conservation of mass does not apply in practice', 'The reactants are never pure elements', 'Some product is lost in transfers, side reactions occur, or the reaction is reversible', 'Some atoms are destroyed'], 'C'),
]

HARD_MOLES = [
    ('6.0 g of magnesium is added to 100 cm³ of 2.0 mol/dm³ hydrochloric acid (Mg + 2HCl → MgCl₂ + H₂). What volume of hydrogen forms at r.t.p.? (Ar: Mg = 24; 1 mol of gas = 24 dm³)',
     ['2.4 dm³', '3 dm³', '4.8 dm³', '6 dm³'], 'A'),
    ('5.4 g of aluminium reacts with 0.20 mol of sulfuric acid (2Al + 3H₂SO₄ → Al₂(SO₄)₃ + 3H₂). What volume of hydrogen forms at r.t.p.? (Ar: Al = 27; 1 mol of gas = 24 dm³)',
     ['4.8 dm³', '9.6 dm³', '7.2 dm³', '14.4 dm³'], 'A'),
    ('50.0 cm³ of 0.20 mol/dm³ BaCl₂ is mixed with 30.0 cm³ of 0.50 mol/dm³ Na₂SO₄. What mass of BaSO₄ precipitates? (Ar: Ba = 137, S = 32, O = 16)',
     ['1.42 g', '3.49 g', '2.33 g', '5.83 g'], 'C'),
    ('25.0 cm³ of 0.10 mol/dm³ AgNO₃ is mixed with 20.0 cm³ of 0.20 mol/dm³ NaCl. What mass of AgCl precipitates? (Ar: Ag = 108, Cl = 35.5)',
     ['0.574 g', '0.933 g', '0.146 g', '0.359 g'], 'D'),
    ('2.0 g of CaCO₃ is added to 50 cm³ of 0.50 mol/dm³ HCl (CaCO₃ + 2HCl → CaCl₂ + H₂O + CO₂). What volume of CO₂ forms at r.t.p.? (Ar: Ca = 40, C = 12, O = 16; 1 mol of gas = 24 dm³)',
     ['600 cm³', '150 cm³', '300 cm³', '480 cm³'], 'C'),
    ('A compound contains 40.0% C, 6.7% H and 53.3% O by mass and has Mr = 180. What is its molecular formula? (Ar: C = 12, H = 1, O = 16)',
     ['C₅H₁₀O₅', 'C₆H₁₂O₆', 'CH₂O', 'C₃H₆O₃'], 'B'),
    ('A compound contains 52.2% C, 13.0% H and 34.8% O by mass and has Mr = 46. What is its molecular formula? (Ar: C = 12, H = 1, O = 16)',
     ['CH₃O', 'C₂H₄O', 'C₄H₁₂O₂', 'C₂H₆O'], 'D'),
    ('A hydrocarbon contains 85.7% C and 14.3% H by mass and has Mr = 84. What is its molecular formula? (Ar: C = 12, H = 1)',
     ['C₃H₆', 'C₅H₁₀', 'CH₂', 'C₆H₁₂'], 'D'),
    ('0.60 g of a compound containing only C, H and O burns to give 0.88 g of CO₂ and 0.36 g of H₂O. Its Mr is 60. What is its molecular formula? (Ar: C = 12, H = 1, O = 16)',
     ['C₃H₈O', 'C₂H₆O', 'C₂H₄O₂', 'CH₂O'], 'C'),
    ('10 cm³ of a gaseous hydrocarbon is burnt in excess oxygen. After cooling to room temperature the gas volume has decreased by 25 cm³; shaking with sodium hydroxide solution removes a further 20 cm³. All volumes are measured at the same temperature and pressure. What is the formula of the hydrocarbon?',
     ['C₂H₄', 'C₃H₈', 'C₂H₂', 'C₂H₆'], 'D'),
    ('10 cm³ of a gaseous hydrocarbon is burnt in excess oxygen. After cooling to room temperature the gas volume has decreased by 30 cm³; shaking with sodium hydroxide solution removes a further 30 cm³. All volumes are measured at the same temperature and pressure. What is the formula of the hydrocarbon?',
     ['C₄H₁₀', 'C₃H₈', 'C₃H₆', 'C₂H₆'], 'B'),
    ('10 cm³ of a gaseous hydrocarbon is burnt in excess oxygen. After cooling to room temperature the gas volume has decreased by 30 cm³; shaking with sodium hydroxide solution removes a further 40 cm³. All volumes are measured at the same temperature and pressure. What is the formula of the hydrocarbon?',
     ['C₄H₈', 'C₃H₆', 'C₄H₁₀', 'C₄H₆'], 'A'),
    ('10 cm³ of a gaseous hydrocarbon is burnt in excess oxygen. After cooling to room temperature the gas volume has decreased by 20 cm³; shaking with sodium hydroxide solution removes a further 10 cm³. All volumes are measured at the same temperature and pressure. What is the formula of the hydrocarbon?',
     ['C₂H₆', 'CH₂', 'CH₄', 'C₂H₄'], 'C'),
    ('5.00 g of hydrated magnesium sulfate, MgSO₄·xH₂O, is heated until its mass is constant at 2.44 g. What is x? (Mr: MgSO₄ = 120, H₂O = 18)',
     ['6', '7', '10', '5'], 'B'),
    ('2.495 g of hydrated copper(II) sulfate, CuSO₄·xH₂O, leaves 1.595 g of anhydrous solid when heated. What is x? (Mr: CuSO₄ = 159.5, H₂O = 18)',
     ['7', '5', '10', '4'], 'B'),
    ('2.86 g of hydrated sodium carbonate, Na₂CO₃·xH₂O, leaves 1.06 g of anhydrous solid when heated. What is x? (Mr: Na₂CO₃ = 106, H₂O = 18)',
     ['10', '12', '7', '5'], 'A'),
    ('1.72 g of hydrated calcium sulfate, CaSO₄·xH₂O, loses 0.36 g of water on heating. What is x? (Mr: CaSO₄ = 136, H₂O = 18)',
     ['2', '7', '1', '5'], 'A'),
    ('5.0 g of impure marble reacts with excess hydrochloric acid to give 1.08 dm³ of CO₂ at r.t.p. What is the percentage of CaCO₃ in the marble? (Ar: Ca = 40, C = 12, O = 16; 1 mol of gas = 24 dm³)',
     ['39.6%', '90%', '21.6%', '96.4%'], 'B'),
    ('3.0 g of impure zinc reacts with excess acid to give 0.96 dm³ of hydrogen at r.t.p. What is the percentage of zinc in the sample? (Ar: Zn = 65; 1 mol of gas = 24 dm³)',
     ['65%', '43.3%', '86.7%', '32%'], 'C'),
    ('2.0 g of impure sodium hydroxide is neutralised by 40.0 cm³ of 1.0 mol/dm³ hydrochloric acid. What is the percentage of NaOH in the sample? (Ar: Na = 23, O = 16, H = 1)',
     ['40%', '80%', '20%', '73%'], 'B'),
    ('Fe₂O₃ + 3CO → 2Fe + 3CO₂. 32.0 kg of Fe₂O₃ gives 17.92 kg of iron. What is the percentage yield? (Ar: Fe = 56, O = 16)',
     ['40%', '56%', '80%', '64%'], 'C'),
    ('N₂ + 3H₂ → 2NH₃. 14 g of nitrogen gives 3.4 g of ammonia. What is the percentage yield? (Ar: N = 14, H = 1)',
     ['10%', '40%', '24.3%', '20%'], 'D'),
    ('C₂H₄ + H₂O → C₂H₅OH. 2.8 g of ethene gives 3.45 g of ethanol. What is the percentage yield? (Ar: C = 12, H = 1, O = 16)',
     ['25%', '56.3%', '75%', '37.5%'], 'C'),
    ('25.0 cm³ of sodium hydroxide solution is neutralised by 18.5 cm³ of 0.200 mol/dm³ sulfuric acid. What is the concentration of the sodium hydroxide?',
     ['0.27 mol/dm³', '0.296 mol/dm³', '0.592 mol/dm³', '0.148 mol/dm³'], 'B'),
    ('1.50 g of impure sodium carbonate is dissolved to make 250 cm³ of solution. 25.0 cm³ of this solution needs 20.0 cm³ of 0.100 mol/dm³ HCl (Na₂CO₃ + 2HCl → 2NaCl + H₂O + CO₂). What is the percentage purity? (Ar: Na = 23, C = 12, O = 16)',
     ['23.6%', '35.3%', '53%', '70.7%'], 'D'),
    ('0.600 g of a monobasic acid HA requires 20.0 cm³ of 0.500 mol/dm³ NaOH for neutralisation. What is the Mr of HA?',
     ['90', '30', '120', '60'], 'D'),
    ('0.90 g of a dibasic acid is neutralised by 20.0 cm³ of 1.00 mol/dm³ NaOH. What is the Mr of the acid?',
     ['22.5', '90', '18', '45'], 'B'),
    ('100 cm³ of 0.20 mol/dm³ NaCl is mixed with 100 cm³ of 0.10 mol/dm³ CaCl₂. What is the concentration of chloride ions in the mixture?',
     ['0.2 mol/dm³', '0.15 mol/dm³', '0.4 mol/dm³', '0.04 mol/dm³'], 'A'),
    ('20.0 cm³ of 1.0 mol/dm³ sulfuric acid is diluted to 200 cm³. What is the concentration of hydrogen ions in the diluted solution?',
     ['0.2 mol/dm³', '0.1 mol/dm³', '0.4 mol/dm³', '0.3 mol/dm³'], 'A'),
    ('10.0 cm³ of 1.00 mol/dm³ solution is diluted to 100 cm³ (solution A). 10.0 cm³ of A is then diluted to 250 cm³. What is the final concentration?',
     ['0.004 mol/dm³', '0.006 mol/dm³', '0.008 mol/dm³', '0.002 mol/dm³'], 'A'),
]

NEW_ELECTROLYSIS = [
    ('How many moles of electrons must be transferred to produce 1 mol of Al³⁺ ions to form aluminium metal?',
     ['6', '3', '2', '4'], 'B'),
    ('How many moles of electrons must be transferred to produce 1 mol of Cu²⁺ ions to form copper metal?',
     ['1', '2', '4', '3'], 'B'),
    ('How many moles of electrons must be transferred to produce 1 mol of Ag⁺ ions to form silver metal?',
     ['4', '3', '1', '2'], 'C'),
    ('How many moles of electrons must be transferred to produce 1 mol of chlorine gas, Cl₂, from chloride ions?',
     ['4', '3', '1', '2'], 'D'),
    ('How many moles of electrons must be transferred to produce 1 mol of oxygen gas, O₂, from oxide ions (O²⁻)?',
     ['3', '4', '8', '2'], 'B'),
    ('How many moles of electrons must be transferred to produce 1 mol of hydrogen gas, H₂, from H⁺ ions?',
     ['3', '4', '2', '1'], 'C'),
    ('Dilute sulfuric acid is electrolysed with inert electrodes and 36 cm³ of hydrogen collects at the cathode. What volume of oxygen collects at the anode (same conditions)?',
     ['36 cm³', '9 cm³', '18 cm³', '72 cm³'], 'C'),
    ('In the electrolysis of water, 15 cm³ of oxygen collects at the anode. What volume of hydrogen collects at the cathode (same conditions)?',
     ['15 cm³', '60 cm³', '7.5 cm³', '30 cm³'], 'D'),
    ('Concentrated sodium chloride solution is electrolysed with inert electrodes. 40 cm³ of hydrogen forms at the cathode. What volume of chlorine forms at the anode (same conditions)?',
     ['40 cm³', '20 cm³', '10 cm³', '80 cm³'], 'A'),
    ('Concentrated sodium chloride solution is electrolysed with inert electrodes. 60 cm³ of chlorine forms at the anode. What volume of hydrogen forms at the cathode (same conditions)?',
     ['15 cm³', '60 cm³', '120 cm³', '30 cm³'], 'B'),
    ('0.20 mol of electrons pass through molten lead(II) bromide. What mass of lead forms at the cathode? (Ar: Pb = 207)',
     ['20.7 g', '82.8 g', '41.4 g', '10.4 g'], 'A'),
    ('0.30 mol of electrons pass through molten aluminium oxide. What mass of aluminium forms at the cathode? (Ar: Al = 27)',
     ['2.7 g', '5.4 g', '16.2 g', '8.1 g'], 'A'),
    ('Which electrode is connected to the negative terminal of the power supply?',
     ['The salt bridge', 'The electrolyte', 'The anode', 'The cathode'], 'D'),
    ('What are the products of the electrolysis of molten lead(II) bromide using inert electrodes?',
     ['Hydrogen at the cathode and bromine at the anode', 'Hydrogen at the cathode and oxygen at the anode', 'Lead at the anode and bromine at the cathode', 'Lead at the cathode and bromine at the anode'], 'D'),
    ('Which substance remains in solution when concentrated aqueous sodium chloride is electrolysed with inert electrodes?',
     ['Sodium hydroxide', 'Sodium oxide', 'Sodium metal', 'Hydrochloric acid'], 'A'),
    ('Why is cryolite added in the extraction of aluminium?',
     ['It reacts with aluminium oxide to form aluminium', 'It removes impurities from the bauxite', 'It acts as the cathode', 'It lowers the melting point of the aluminium oxide'], 'D'),
    ('Why must the graphite anodes in aluminium extraction be replaced regularly?',
     ['They are reduced to carbon monoxide at the cathode', 'They dissolve in cryolite', 'They burn away in the oxygen produced', 'They become coated with aluminium'], 'C'),
    ('In the electrolysis of dilute sulfuric acid, what is the ratio of the volume of hydrogen to oxygen collected?',
     ['4 : 1', '2 : 1', '1 : 2', '1 : 1'], 'B'),
    ('Which ion is discharged at the cathode when aqueous copper(II) sulfate is electrolysed with inert electrodes?',
     ['SO₄²⁻', 'H⁺', 'Cu²⁺', 'OH⁻'], 'C'),
    ('What is seen at the cathode when aqueous copper(II) sulfate is electrolysed with inert electrodes?',
     ['Bubbles of oxygen form', 'A pink-brown solid forms', 'The electrode dissolves', 'A silvery liquid forms'], 'B'),
    ('Aqueous copper(II) sulfate is electrolysed with copper electrodes. What happens to the anode?',
     ['Oxygen forms on it', 'Nothing happens', 'It gains mass', 'It dissolves and loses mass'], 'D'),
    ('A spoon is to be silver-plated. How should it be connected?',
     ['As the anode, in silver nitrate solution', 'As the cathode, in copper(II) sulfate solution', 'As the anode, in dilute acid', 'As the cathode, in silver nitrate solution'], 'D'),
    ('Which solution would be used as the electrolyte to silver-plate a spoon?',
     ['Copper(II) sulfate solution', 'Dilute sulfuric acid', 'Sodium chloride solution', 'Silver nitrate solution'], 'D'),
    ('Which of these is NOT a use of electrolysis?',
     ['Extracting aluminium', 'Purifying copper', 'Fractional distillation of crude oil', 'Electroplating'], 'C'),
    ('Aqueous sodium sulfate is electrolysed using inert electrodes. Which gas forms at the anode?',
     ['Oxygen', 'Sulfur trioxide', 'Hydrogen', 'Sulfur dioxide'], 'A'),
    ('What are the products of the electrolysis of molten potassium iodide?',
     ['Potassium and oxygen', 'Hydrogen and oxygen', 'Potassium and iodine', 'Hydrogen and iodine'], 'C'),
    ('Why can ionic compounds conduct electricity when molten?',
     ['They contain free molecules', 'Their ions are free to move', 'Their electrons are free to move', 'They contain delocalised electrons'], 'B'),
    ('Which half-equation describes the reaction at the cathode in the extraction of aluminium?',
     ['2O²⁻ → O₂ + 4e⁻', 'Al³⁺ → Al + 3e⁻', 'Al³⁺ + 3e⁻ → Al', 'Al → Al³⁺ + 3e⁻'], 'C'),
    ('Which of these substances is a non-electrolyte?',
     ['Molten sodium chloride', 'Dilute sulfuric acid', 'Ethanol', 'Aqueous copper(II) sulfate'], 'C'),
    ('In an electrolysis circuit, electrons flow:',
     ['From the anode, through the external circuit, to the cathode', 'Through the electrolyte from the cathode to the anode', 'Through the electrolyte from the anode to the cathode', 'From the cathode, through the external circuit, to the anode'], 'A'),
    ('What is meant by an inert electrode?',
     ['It is the electrode that gains mass', 'It does not take part in the electrolysis reaction', 'It dissolves in the electrolyte', 'It is always made of platinum'], 'B'),
    ('Which ions are present in dilute sulfuric acid?',
     ['H⁺ and SO₄²⁻ only', 'S²⁻ and O²⁻', 'H₂ and SO₄', 'H⁺, OH⁻ and SO₄²⁻'], 'D'),
    ('What happens to the colour of the electrolyte when aqueous copper(II) sulfate is electrolysed with inert electrodes?',
     ['It turns darker blue', 'It turns green', 'The blue colour fades', 'It stays the same'], 'C'),
    ('What is observed at the anode when concentrated hydrochloric acid is electrolysed?',
     ['A pale green gas that bleaches damp litmus paper', 'A colourless gas that burns with a squeaky pop', 'A colourless gas that relights a glowing splint', 'A brown liquid forms'], 'A'),
    ('Which test shows that chlorine has formed at the anode?',
     ['Damp red litmus paper turns blue', 'Damp blue litmus paper turns red and then white', 'A glowing splint relights', 'Limewater turns milky'], 'B'),
    ('Which test shows that oxygen has formed at the anode?',
     ['A glowing splint relights', 'Limewater turns milky', 'A lighted splint gives a squeaky pop', 'Damp litmus paper is bleached'], 'A'),
    ('Which ions are discharged when dilute aqueous sodium hydroxide is electrolysed with inert electrodes?',
     ['H⁺ and OH⁻', 'Na⁺ and OH⁻', 'H⁺ and O²⁻', 'Na⁺ and H⁺'], 'A'),
    ('Why is hydrogen, not sodium, formed at the cathode when aqueous sodium chloride is electrolysed?',
     ['Sodium reacts with chlorine', 'H⁺ ions are discharged in preference to Na⁺ ions', 'Sodium is too unreactive', 'Sodium ions are not present in the solution'], 'B'),
    ('Which metal is extracted industrially by the electrolysis of its molten chloride?',
     ['Sodium', 'Zinc', 'Copper', 'Iron'], 'A'),
    ('Which is the anode reaction in the extraction of aluminium?',
     ['2Cl⁻ → Cl₂ + 2e⁻', 'Al³⁺ + 3e⁻ → Al', '4OH⁻ → 2H₂O + O₂ + 4e⁻', '2O²⁻ → O₂ + 4e⁻'], 'D'),
    ('What effect does increasing the current have on the electrolysis of molten sodium chloride for the same time?',
     ['Different products are formed', 'More product is formed', 'No change at all', 'Less product is formed'], 'B'),
    ('Why is steel sometimes plated with chromium?',
     ['To make it lighter', 'To make it magnetic', 'To protect it from corrosion and improve its appearance', 'To make it conduct electricity better'], 'C'),
    ('What is formed at the anode when molten zinc chloride is electrolysed with inert electrodes?',
     ['Oxygen', 'Chlorine', 'Zinc', 'Hydrogen'], 'B'),
    ('In the purification of copper, what happens to impurities such as silver and gold?',
     ['They fall to the bottom as anode sludge', 'They form gases at the anode', 'They dissolve in the electrolyte', 'They plate onto the cathode'], 'A'),
    ('What is used as the cathode in the purification of copper?',
     ['A block of impure copper', 'Graphite', 'A thin sheet of pure copper', 'Platinum'], 'C'),
    ('Aqueous copper(II) sulfate is electrolysed using copper electrodes. What happens to the colour of the solution?',
     ['It stays blue', 'It fades to colourless', 'It becomes darker blue', 'It turns green'], 'A'),
    ('Dilute sulfuric acid is electrolysed for a long time. What happens to the concentration of the acid?',
     ['It becomes zero', 'It stays exactly the same because no acid is used', 'It decreases because acid is used up', 'It increases because water is used up'], 'D'),
    ('Which is the cathode half-equation for the formation of hydrogen?',
     ['2H⁺ → H₂ + 2e⁻', 'H₂ → 2H⁺ + 2e⁻', 'H⁺ + e⁻ → H₂', '2H⁺ + 2e⁻ → H₂'], 'D'),
]

HARD_ELECTROLYSIS = [
    ('The same current flows for the same time through two cells in series, one containing aqueous copper(II) sulfate and one aqueous silver nitrate (both with inert electrodes). 0.64 g of copper forms in the first cell. What mass of silver forms in the second? (Ar: Cu = 64, Ag = 108)',
     ['1.08 g', '0.54 g', '2.16 g', '4.32 g'], 'C'),
    ('The same charge passes through aluminium oxide (molten) and copper(II) sulfate solution in series. 2.7 g of aluminium forms. What mass of copper forms? (Ar: Al = 27, Cu = 63.5)',
     ['6.35 g', '9.53 g', '4.23 g', '19.1 g'], 'B'),
    ('The same charge passes through molten sodium chloride and molten magnesium chloride in series. 2.3 g of sodium forms. What mass of magnesium forms? (Ar: Na = 23, Mg = 24)',
     ['1.2 g', '4.8 g', '2.2 g', '2.4 g'], 'A'),
    ('In a cell with silver nitrate and inert electrodes, 0.216 g of silver is deposited. The same charge passes through dilute sulfuric acid in a second cell. What volume of oxygen forms there at r.t.p.? (Ar: Ag = 108; 1 mol of gas = 24 dm³)',
     ['6 cm³', '24 cm³', '48 cm³', '12 cm³'], 'D'),
    ('A current of 0.50 A flows for 1930 s through aqueous copper(II) sulfate with inert electrodes. What mass of copper is deposited? (1 mol of electrons carries 96 500 C; Ar: Cu = 63.5)',
     ['0.318 g', '0.635 g', '0.953 g', '0.159 g'], 'A'),
    ('A current of 2.0 A flows for 965 s through aqueous silver nitrate with inert electrodes. What mass of silver is deposited? (1 mol of electrons carries 96 500 C; Ar: Ag = 108)',
     ['1.08 g', '0.54 g', '2.16 g', '4.32 g'], 'C'),
    ('A current of 0.40 A flows for 4825 s through dilute sulfuric acid. What volume of hydrogen forms at r.t.p.? (1 mol of electrons carries 96 500 C; 1 mol of gas = 24 000 cm³)',
     ['240 cm³', '480 cm³', '224 cm³', '120 cm³'], 'A'),
    ('For how long must a current of 0.50 A flow to deposit 1.08 g of silver from silver nitrate solution? (1 mol of electrons carries 96 500 C; Ar: Ag = 108)',
     ['1930 s', '482.5 s', '3860 s', '965 s'], 'A'),
    ('11.5 g of sodium forms during the electrolysis of molten sodium chloride. What volume of chlorine forms at the anode at r.t.p.? (Ar: Na = 23; 1 mol of gas = 24 dm³)',
     ['24 dm³', '6 dm³', '3 dm³', '12 dm³'], 'B'),
    ('50 cm³ of 0.10 mol/dm³ copper(II) sulfate is completely electrolysed using inert electrodes. What volume of oxygen forms at the anode at r.t.p.? (1 mol of gas = 24 000 cm³)',
     ['30 cm³', '120 cm³', '240 cm³', '60 cm³'], 'D'),
    ('Aqueous silver nitrate is electrolysed using silver electrodes. The cathode gains 2.16 g. By how much does the mass of the anode change?',
     ['0.54 g decrease', '1.08 g decrease', '4.32 g decrease', '2.16 g decrease'], 'D'),
    ('How many moles of electrons are needed to produce 54 g of aluminium from molten aluminium oxide? (Ar: Al = 27)',
     ['2 mol', '8 mol', '4 mol', '6 mol'], 'D'),
    ('How many moles of oxygen gas form at the anode when 2.0 mol of aluminium are produced from molten aluminium oxide?',
     ['2 mol', '0.5 mol', '3 mol', '1.5 mol'], 'D'),
    ('What mass of aluminium is produced by a charge of 96 500 C passing through molten aluminium oxide? (1 mol of electrons carries 96 500 C; Ar: Al = 27)',
     ['9 g', '27 g', '18 g', '13.5 g'], 'A'),
    ('100 cm³ of 0.50 mol/dm³ copper(II) sulfate is electrolysed with inert electrodes until 1.27 g of copper has formed. What is the final concentration of copper(II) ions? (Ar: Cu = 63.5; ignore volume changes)',
     ['0.2 mol/dm³', '0.3 mol/dm³', '0.4 mol/dm³', '0.5 mol/dm³'], 'B'),
    ('Why does the solution become acidic when aqueous copper(II) sulfate is electrolysed with inert electrodes?',
     ['Copper ions react with water to form acid', 'Hydrogen ions are discharged at the cathode', 'OH⁻ ions are discharged at the anode, leaving H⁺ and SO₄²⁻ ions in solution', 'Sulfate ions are discharged at the anode'], 'C'),
    ('How does the pH of the solution near the cathode change during the electrolysis of concentrated brine using inert electrodes?',
     ['It decreases because H⁺ ions are left behind', 'It increases because OH⁻ ions are left behind', 'It decreases because chlorine dissolves', 'It stays at 7'], 'B'),
    ('A solution contains Cu²⁺, Na⁺ and H⁺ ions. Which ion is discharged first at the cathode?',
     ['H⁺', 'Cu²⁺', 'They are all discharged at the same time', 'Na⁺'], 'B'),
    ('Aqueous copper(II) sulfate is electrolysed first with graphite electrodes and then with copper electrodes. Why do the anode products differ?',
     ['Graphite dissolves, but copper does not', 'Copper electrodes are inert and graphite is not', 'A copper anode is itself oxidised in preference to hydroxide ions being discharged', 'Sulfate ions are discharged at a copper anode'], 'C'),
    ('Aqueous sodium sulfate with universal indicator is electrolysed using inert electrodes. What colours appear near the electrodes?',
     ['Red near the cathode and purple near the anode', 'Purple at both electrodes', 'Green at both electrodes', 'Purple near the cathode and red near the anode'], 'D'),
    ('Why is twice as much hydrogen as oxygen formed in the electrolysis of dilute sulfuric acid?',
     ['Water contains twice as many oxygen atoms as hydrogen atoms', 'Two electrons form one H₂ molecule but four electrons are needed for one O₂ molecule', 'Hydrogen is lighter than oxygen', 'Hydrogen is more soluble than oxygen'], 'B'),
    ('In the electrolytic refining of copper the concentration of Cu²⁺ ions in the electrolyte stays constant. Why?',
     ['The electrolyte is replaced continuously', 'Copper dissolves at the anode at the same rate as it is deposited at the cathode', 'Hydrogen ions replace copper ions', 'No copper is deposited at the cathode'], 'B'),
    ('Why can aluminium not be obtained by the electrolysis of aqueous aluminium sulfate?',
     ['Aluminium sulfate is insoluble', 'Sulfate ions are discharged at the cathode', 'Aluminium is too dense', 'Hydrogen ions are discharged at the cathode in preference to aluminium ions'], 'D'),
    ('Why must the products be kept apart in the electrolysis of molten sodium chloride?',
     ['The products would explode as gases', 'Chlorine would dissolve in sodium', 'Sodium and chlorine would react together to re-form sodium chloride', 'Sodium would react with the electrodes'], 'C'),
    ('Which half-equation shows the formation of oxygen from hydroxide ions?',
     ['OH⁻ → O₂ + H⁺ + e⁻', '4OH⁻ → 2H₂O + O₂ + 4e⁻', '4OH⁻ + 4e⁻ → 2H₂O + O₂', '2OH⁻ → H₂O + O₂ + 2e⁻'], 'B'),
    ('What is the cathode product when molten and when concentrated aqueous sodium chloride are electrolysed?',
     ['Sodium from the molten salt and hydrogen from the solution', 'Hydrogen from both', 'Hydrogen from the molten salt and sodium from the solution', 'Sodium from both'], 'A'),
    ('Which statement about the electrolysis of dilute sulfuric acid with inert electrodes is correct?',
     ['Water is used up, so the acid becomes more concentrated', 'The pH rises steadily', 'Sulfate ions are discharged at the anode', 'The acid is used up, so the solution becomes less acidic'], 'A'),
    ('Which statement about the graphite anodes in aluminium extraction is correct?',
     ['They are slowly oxidised to carbon dioxide by the oxygen produced', 'They do not conduct electricity', 'They react with cryolite', 'They are reduced to carbon at the cathode'], 'A'),
    ('During silver plating, what happens to the mass of the silver anode and to the concentration of silver ions in the electrolyte?',
     ['The anode gains mass and the concentration decreases', 'The anode stays the same and the concentration increases', 'The anode loses mass and the concentration stays constant', 'The anode loses mass and the concentration decreases'], 'C'),
    ('Which ions are present in electrolysed concentrated sodium chloride solution after electrolysis has finished?',
     ['Na⁺ and Cl⁻', 'H⁺ and Cl⁻', 'Na⁺ and OH⁻', 'H⁺ and OH⁻'], 'C'),
]

NEW_ORGANIC = [
    ('How many hydrogen atoms are in a molecule of the alkane with 7 carbon atoms?',
     ['15', '16', '14', '18'], 'B'),
    ('How many hydrogen atoms are in a molecule of the alkane with 12 carbon atoms?',
     ['26', '24', '25', '28'], 'A'),
    ('An alkene has 12 hydrogen atoms in each molecule. How many carbon atoms does it have?',
     ['5', '6', '7', '12'], 'B'),
    ('What is the relative formula mass of pentane, C₅H₁₂? (Ar: C = 12, H = 1)',
     ['60', '70', '72', '84'], 'C'),
    ('What is the relative formula mass of octane, C₈H₁₈? (Ar: C = 12, H = 1)',
     ['96', '114', '126', '112'], 'B'),
    ('What is the percentage by mass of carbon in methane, CH₄? (Ar: C = 12, H = 1)',
     ['75%', '80%', '37.5%', '25%'], 'A'),
    ('What is the percentage by mass of carbon in ethene, C₂H₄? (Ar: C = 12, H = 1)',
     ['80%', '42.9%', '85.7%', '75%'], 'C'),
    ('A sample of poly(ethene) has a relative formula mass of 28 000. How many ethene molecules joined to form one polymer molecule? (Ar: C = 12, H = 1)',
     ['1500', '2000', '500', '1000'], 'D'),
    ('What is the name of the alkane with three carbon atoms?',
     ['Propene', 'Propane', 'Propanol', 'Butane'], 'B'),
    ('What is the molecular formula of butene?',
     ['C₄H₁₀', 'C₄H₈', 'C₃H₆', 'C₄H₆'], 'B'),
    ('What is the structural formula of propan-1-ol?',
     ['CH₃CH(OH)CH₃', 'CH₃CH₂CHO', 'CH₃CH₂COOH', 'CH₃CH₂CH₂OH'], 'D'),
    ('Which process is used to separate crude oil into fractions?',
     ['Cracking', 'Crystallisation', 'Fractional distillation', 'Filtration'], 'C'),
    ('Which fraction of crude oil has the highest boiling range?',
     ['Petrol', 'Kerosene', 'Bitumen', 'Refinery gases'], 'C'),
    ('Which fraction of crude oil is used as aircraft fuel?',
     ['Kerosene', 'Lubricating oil', 'Bitumen', 'Refinery gas'], 'A'),
    ('Why do longer-chain hydrocarbons have higher boiling points?',
     ['Stronger covalent bonds within each molecule', 'They contain ions', 'They contain double bonds', 'Stronger forces between their molecules'], 'D'),
    ('What is cracking?',
     ['Burning hydrocarbons in oxygen', 'Breaking long-chain alkanes into shorter alkanes and alkenes', 'Separating crude oil by boiling point', 'Joining small molecules into long chains'], 'B'),
    ('What is used as the catalyst in the cracking of hydrocarbons in the laboratory?',
     ['Iron', 'Vanadium(V) oxide', 'Aluminium oxide', 'Nickel'], 'C'),
    ('What is the product of the reaction between ethene and bromine?',
     ['Ethanol', 'Dibromomethane', '1,2-dibromoethane', 'Bromoethane'], 'C'),
    ('Which conditions are used to make ethanol from ethene and steam?',
     ['Nickel catalyst at 150 °C', 'Phosphoric acid catalyst, about 300 °C and high pressure', 'Yeast at 35 °C', 'Concentrated sulfuric acid at room temperature'], 'B'),
    ('Which conditions are best for fermentation of glucose to make ethanol?',
     ['Nickel catalyst, 60 °C', 'Yeast, about 30–40 °C, no oxygen', 'Yeast, 100 °C, plenty of oxygen', 'Acid catalyst, 300 °C, high pressure'], 'B'),
    ('Which reagent oxidises ethanol to ethanoic acid?',
     ['Acidified potassium manganate(VII)', 'Dilute hydrochloric acid', 'Hydrogen with a nickel catalyst', 'Sodium hydroxide solution'], 'A'),
    ('Ethanol and ethanoic acid react in the presence of concentrated sulfuric acid to form:',
     ['Methyl methanoate', 'Ethene', 'Ethane', 'Ethyl ethanoate'], 'D'),
    ('What is the name of the ester made from methanol and propanoic acid?',
     ['Ethyl propanoate', 'Propyl methanoate', 'Methyl propanoate', 'Methyl ethanoate'], 'C'),
    ('Which functional group is present in an ester?',
     ['–COO–', '–COOH', '–OH', 'C=C'], 'A'),
    ('What is observed when ethanoic acid is added to sodium carbonate?',
     ['Effervescence', 'The mixture turns orange', 'Nothing happens', 'A white precipitate forms'], 'A'),
    ('Why is ethanoic acid classified as a weak acid?',
     ['It does not react with metals', 'It contains only one hydrogen atom', 'It has a high pH because it is a base', 'It is only partially ionised in water'], 'D'),
    ('What is the repeat unit of poly(ethene)?',
     ['–CH₃–CH₃–', '–CH₂–CH₂–', '–CH=CH–', '–CH₂–CH₂–CH₂–'], 'B'),
    ('What is the monomer used to make poly(propene)?',
     ['Propene', 'Propane', 'Ethene', 'Propanol'], 'A'),
    ('Why is the polymerisation of ethene called addition polymerisation?',
     ['Each monomer adds a halogen', 'A small molecule is lost each time', 'The monomers add together with no other product formed', 'Water is added to the monomers'], 'C'),
    ('Which polymer is formed by condensation polymerisation?',
     ['Nylon', 'Poly(chloroethene)', 'Poly(propene)', 'Poly(ethene)'], 'A'),
    ('What small molecule is lost when nylon forms from a diamine and a dicarboxylic acid?',
     ['Ammonia', 'Carbon dioxide', 'Hydrogen', 'Water'], 'D'),
    ('Why are most plastics a problem for the environment?',
     ['They are made from metals', 'They are all poisonous gases', 'They are not biodegradable', 'They dissolve in rain'], 'C'),
    ('What is a problem caused by burning plastics?',
     ['Metals are produced', 'Oxygen is produced', 'Water is produced', 'Toxic gases are produced'], 'D'),
    ('Which gas is produced by the incomplete combustion of a hydrocarbon?',
     ['Chlorine', 'Hydrogen', 'Carbon monoxide', 'Nitrogen'], 'C'),
    ('Which pair are structural isomers?',
     ['Propane and propene', 'Butane and methylpropane', 'Ethane and ethene', 'Ethanol and ethanoic acid'], 'B'),
    ('How does the flammability of alkanes change as the carbon chain gets longer?',
     ['It increases', 'It stays the same', 'It disappears at 3 carbons', 'It decreases'], 'D'),
    ('What products form when methane reacts with chlorine in sunlight?',
     ['Carbon and hydrogen chloride', 'Carbon tetrachloride only', 'Chloromethane and hydrogen chloride', 'Ethane and chlorine'], 'C'),
    ('Why is ultraviolet light needed for the reaction between methane and chlorine?',
     ['It acts as a catalyst', 'It dissolves the chlorine', 'It breaks the C=C bond', 'It supplies the energy to break the Cl–Cl bond'], 'D'),
    ('What is formed when ethene reacts with hydrogen using a nickel catalyst?',
     ['Ethane', 'Ethanol', 'Ethyne', 'Propene'], 'A'),
    ('Why is hydrogenation of vegetable oils carried out?',
     ['To make margarine, which is solid at room temperature', 'To make them dissolve in water', 'To make them acidic', 'To make the oils burn faster'], 'A'),
    ('Which is the formula of ethanoic acid?',
     ['CH₃COOCH₃', 'CH₃COOH', 'CH₃CH₂OH', 'CH₃CHO'], 'B'),
    ('Which compound contains the –OH functional group?',
     ['Ethane', 'Ethene', 'Ethanol', 'Ethyl ethanoate'], 'C'),
    ('Why can ethanol be separated from a fermentation mixture by fractional distillation?',
     ['Ethanol and water have different boiling points', 'Ethanol is a solid', 'Ethanol is denser than water', 'Ethanol is insoluble in water'], 'A'),
    ('What is the general formula of the alkenes?',
     ['CnH2n', 'CnHn', 'CnH2n−2', 'CnH2n+2'], 'A'),
    ('Which statement about the alkanes is correct?',
     ['They contain double bonds', 'They decolourise bromine water', 'They are all liquids at room temperature', 'They are saturated and only contain single bonds'], 'D'),
    ('Which fraction of crude oil is the most viscous?',
     ['Petrol', 'Naphtha', 'Kerosene', 'Bitumen'], 'D'),
    ('Why do fractions with smaller molecules rise higher in a fractionating column?',
     ['They are denser', 'They are less flammable', 'They have higher boiling points', 'They have lower boiling points'], 'D'),
    ('What type of reaction is C₂H₅OH + CH₃COOH ⇌ CH₃COOC₂H₅ + H₂O?',
     ['Addition polymerisation', 'Esterification', 'Fermentation', 'Cracking'], 'B'),
]

HARD_ORGANIC = [
    ('How many structural isomers does pentane, C₅H₁₂, have (including pentane itself)?',
     ['3', '2', '4', '5'], 'A'),
    ('How many structural isomers of C₄H₈ are alkenes?',
     ['5', '3', '4', '2'], 'B'),
    ('How many structural isomers of C₄H₁₀O are alcohols?',
     ['5', '2', '3', '4'], 'D'),
    ('How many structural isomers does C₃H₇Br have?',
     ['3', '2', '1', '4'], 'B'),
    ('10 cm³ of a gaseous hydrocarbon is burnt in excess oxygen. After cooling to room temperature the gas volume has decreased by 20 cm³, and a further 20 cm³ is absorbed by sodium hydroxide solution. All volumes are measured under the same conditions. What is the hydrocarbon?',
     ['C₃H₆', 'C₂H₂', 'C₂H₆', 'C₂H₄'], 'D'),
    ('10 cm³ of a gaseous hydrocarbon is burnt in excess oxygen. After cooling to room temperature the gas volume has decreased by 25 cm³, and a further 30 cm³ is absorbed by sodium hydroxide solution. All volumes are measured under the same conditions. What is the hydrocarbon?',
     ['C₄H₈', 'C₃H₆', 'C₃H₈', 'C₂H₄'], 'B'),
    ('10 cm³ of a gaseous hydrocarbon is burnt in excess oxygen. After cooling to room temperature the gas volume has decreased by 15 cm³, and a further 20 cm³ is absorbed by sodium hydroxide solution. All volumes are measured under the same conditions. What is the hydrocarbon?',
     ['CH₄', 'C₂H₄', 'C₂H₂', 'C₃H₄'], 'C'),
    ('A compound contains 54.5% C, 9.1% H and 36.4% O by mass and has Mr = 88. What is its molecular formula? (Ar: C = 12, H = 1, O = 16)',
     ['C₃H₆O₂', 'C₄H₁₀O', 'C₂H₄O', 'C₄H₈O₂'], 'D'),
    ('A hydrocarbon contains 92.3% C and 7.7% H by mass and has Mr = 26. What is its molecular formula? (Ar: C = 12, H = 1)',
     ['C₂H₂', 'CH', 'C₄H₄', 'C₂H₄'], 'A'),
    ('A compound contains 40.0% C, 6.7% H and 53.3% O by mass and has Mr = 60. What is its molecular formula? (Ar: C = 12, H = 1, O = 16)',
     ['CH₂O', 'C₂H₄O₂', 'C₂H₆O', 'C₃H₆O₂'], 'B'),
    ('A sample of poly(chloroethene) has a relative formula mass of 62 500. How many monomer units does one molecule contain? (Ar: C = 12, H = 1, Cl = 35.5)',
     ['1000', '2000', '500', '1250'], 'A'),
    ('A sample of poly(propene) has a relative formula mass of 21 000. How many monomer units does one molecule contain? (Ar: C = 12, H = 1)',
     ['750', '250', '500', '1000'], 'C'),
    ('Nylon is made from H₂N(CH₂)₆NH₂ (Mr = 116) and HOOC(CH₂)₄COOH (Mr = 146). What is the relative formula mass of its repeat unit, formed by losing two molecules of water? (Mr of water = 18)',
     ['226', '244', '262', '208'], 'A'),
    ('A polymer has the repeat unit –CH₂–CHCl–. What is its monomer?',
     ['Chloromethane', 'Chloroethene', 'Chloroethane', 'Dichloroethene'], 'B'),
    ('A polymer has the repeat unit –CF₂–CF₂–. What is its monomer?',
     ['Difluoroethane', 'Tetrafluoroethene', 'Fluoroethene', 'Tetrafluoroethane'], 'B'),
    ('What is the name of the ester made from ethanol and propanoic acid?',
     ['Propyl ethanoate', 'Propyl propanoate', 'Ethyl propanoate', 'Ethyl ethanoate'], 'C'),
    ('Methyl ethanoate is hydrolysed by heating with aqueous sodium hydroxide followed by acidification. Which two compounds form?',
     ['Methanol and methanoic acid', 'Ethanol and methanoic acid', 'Ethanol and ethanoic acid', 'Methanol and ethanoic acid'], 'D'),
    ('Which acid and alcohol would be used to make the ester ethyl methanoate?',
     ['Methanoic acid and ethanol', 'Ethanoic acid and methanol', 'Ethanoic acid and ethanol', 'Methanoic acid and methanol'], 'A'),
    ('Decane, C₁₀H₂₂, is cracked into octane, C₈H₁₈, and one other product. What is the other product?',
     ['C₂H₄', 'C₂H₂', 'C₃H₆', 'C₂H₆'], 'A'),
    ('C₁₀H₂₂ → C₂H₆ + 2C₂H₄ + X. What is the formula of X?',
     ['C₄H₈', 'C₆H₁₂', 'C₄H₁₀', 'C₂H₄'], 'A'),
    ('Butane burns completely: 2C₄H₁₀ + 13O₂ → 8CO₂ + 10H₂O. What mass of carbon dioxide forms from 11.6 g of butane? (Ar: C = 12, H = 1, O = 16)',
     ['35.2 g', '17.6 g', '8.8 g', '70.4 g'], 'A'),
    ('Ethanol burns completely: C₂H₅OH + 3O₂ → 2CO₂ + 3H₂O. What mass of carbon dioxide forms from 4.6 g of ethanol? (Ar: C = 12, H = 1, O = 16)',
     ['4.4 g', '17.6 g', '8.8 g', '13.2 g'], 'C'),
    ('Which reagent distinguishes ethanoic acid from ethanol?',
     ['Litmus paper only', 'Sodium carbonate solution', 'Bromine water', 'Water'], 'B'),
    ('Which test distinguishes propan-1-ol from propanoic acid?',
     ['Add water; only the acid dissolves', 'Burn each; only the alcohol burns', 'Add sodium carbonate; only the acid fizzes', 'Add bromine water; only the alcohol decolourises it'], 'C'),
    ('What colour change is seen when ethanol is oxidised by acidified potassium dichromate(VI)?',
     ['Green to orange', 'Orange to green', 'Colourless to orange', 'Purple to colourless'], 'B'),
    ('What is formed when propan-1-ol is heated with excess acidified potassium manganate(VII)?',
     ['Propane', 'Propyl propanoate', 'Propanoic acid', 'Propene'], 'C'),
    ('Why does ethanol have a much higher boiling point than ethane?',
     ['Ethanol has a larger number of carbon atoms', 'Ethanol has stronger covalent bonds', 'The –OH group gives stronger forces between ethanol molecules', 'Ethanol is ionic'], 'C'),
    ('What is formed when ethene reacts with hydrogen bromide?',
     ['Bromoethene', '1,2-dibromoethane', 'Ethanol', 'Bromoethane'], 'D'),
    ('Which statement about ethene and steam in the manufacture of ethanol is correct?',
     ['It is a reaction with a low atom economy', 'It is a condensation reaction that releases water', 'It is a substitution reaction', 'It is an addition reaction with 100% atom economy'], 'D'),
    ('A compound of formula C₂H₄O₂ gives off carbon dioxide with sodium carbonate. What is it?',
     ['Ethanal', 'Methyl methanoate', 'Ethanol', 'Ethanoic acid'], 'D'),
]

# questions marked 'extremely difficult' (30 per chapter)
HARD_QUESTIONS = {q for q, _, _ in HARD_BONDS + HARD_ATOMIC + HARD_MOLES + HARD_ELECTROLYSIS + HARD_ORGANIC}


def build_pools(old_bonds, old_atomic, old_moles, old_electrolysis, old_organic):
    """Return the dict the quiz uses: every chapter = original questions + new medium + 30 extremely difficult."""
    # a question that said "the above reaction" only makes sense in a fixed order, so make it stand alone
    fixed = []
    for item in old_bonds:
        if item[0].startswith("The ionic equation for the above reaction"):
            item = ("What is the ionic equation for the reaction AgNO₃(aq) + NaCl(aq) → AgCl(s) + NaNO₃(aq)?",
                    item[1], item[2])
        fixed.append(item)
    bonds = fixed + NEW_BONDS + HARD_BONDS
    atomic = list(old_atomic) + NEW_ATOMIC + HARD_ATOMIC
    moles = list(old_moles) + NEW_MOLES + HARD_MOLES
    electrolysis = list(old_electrolysis) + NEW_ELECTROLYSIS + HARD_ELECTROLYSIS
    organic = list(old_organic) + NEW_ORGANIC + HARD_ORGANIC
    return {
        "Mixed (All Chapters)": bonds + atomic + moles + electrolysis + organic,
        "Chemical Bonds & Reactions": bonds,
        "Atomic Structure & Periodic Table": atomic,
        "Moles & Stoichiometry": moles,
        "Electrolysis": electrolysis,
        "Organic Chemistry": organic,
    }
